In [4]:
#!pip install xgboost
!pip install syft==0.5.0

/home/user-010/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/x509.py:17: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  utils.DeprecatedIn35,
  Using cached syft-0.5.0-py2.py3-none-any.whl (504 kB)
  Using cached PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.


In [1]:
import syft as sy

In [2]:
duet = sy.launch_duet(loopback=True)

🎤  🎸  ♪♪♪ Starting Duet ♫♫♫  🎻  🎹

♫♫♫ > DISCLAIMER: Duet is an experimental feature currently in beta.
♫♫♫ > Use at your own risk.


    > ❤️ Love Duet? Please consider supporting our community!
    > https://github.com/sponsors/OpenMined

♫♫♫ > Punching through firewall to OpenGrid Network Node at:
♫♫♫ > http://ec2-18-218-7-180.us-east-2.compute.amazonaws.com:5000
♫♫♫ >
♫♫♫ > ...waiting for response from OpenGrid Network... 
♫♫♫ > DONE!

♫♫♫ > STEP 1: Send the following code to your Duet Partner!

import syft as sy
duet = sy.join_duet(loopback=True)

♫♫♫ > Connecting...


/home/user-010/anaconda3/envs/pysyft/lib/python3.7/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
/home/user-010/anaconda3/envs/pysyft/lib/python3.7/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore



♫♫♫ > CONNECTED!



In [3]:
from sklearn import datasets
import torch as th
import pandas as pd
import numpy as np
import torch as th
import torch.nn as nn
import time
#import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [4]:
#dataset = pd.read_csv('Crop_Artharva.csv')
dat = pd.read_csv('Crop_data_Artharva12.csv')
dat1 = pd.read_csv('Crop_target_Artharva12.csv')
X = dat.iloc[:,0:5].values
y = dat1.iloc[:,0].values
print(X[0:5])
print(X)


[[ 20.41  82.21   7.59 245.15]
 [ 25.76  83.52   5.88 245.66]
 [ 20.62  83.77   6.93 279.55]
 [ 21.84  80.73   6.95 202.38]
 [ 20.08  83.29   5.74 263.64]]
[[ 20.41  82.21   7.59 245.15]
 [ 25.76  83.52   5.88 245.66]
 [ 20.62  83.77   6.93 279.55]
 [ 21.84  80.73   6.95 202.38]
 [ 20.08  83.29   5.74 263.64]
 [ 24.46  82.75   6.74 182.56]
 [ 21.14  80.34   5.59 198.67]
 [ 25.79  82.11   6.95 243.51]
 [ 23.64  80.29   5.01 263.11]
 [ 23.43  80.57   6.36 269.5 ]
 [ 24.98  83.89   6.88 204.8 ]
 [ 22.73  82.17   7.3  260.89]
 [ 24.87  82.84   6.59 295.61]
 [ 21.32  83.     7.28 192.32]
 [ 26.29  84.57   7.02 257.49]
 [ 22.23  81.86   6.94 278.08]
 [ 26.73  81.79   7.87 280.4 ]
 [ 24.89  81.98   5.01 185.95]
 [ 26.88  81.46   6.14 194.58]
 [ 22.68  83.73   7.52 200.91]
 [ 26.09  80.38   5.71 182.9 ]
 [ 25.43  82.95   5.76 195.36]
 [ 26.4   81.06   6.35 223.37]
 [ 26.04  84.97   6.   186.75]
 [ 25.28  80.54   5.45 220.12]
 [ 22.09  83.47   6.37 231.74]
 [ 23.29  81.43   5.11 242.32]
 [ 25.4

In [5]:
print(len(X))

150


In [6]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
from sklearn.preprocessing import StandardScaler
df2 = StandardScaler().fit_transform(dat.iloc[:, 0:5])

In [8]:
X11 = th.FloatTensor(df2)
y11 = th.FloatTensor(y)

In [14]:
X2 = X11.tag("Crops-data")
y2 = y11.tag("Crops-target")
X2 = X11.describe(
   "This is a dataset for crops classification with temperature, humidity, Ph level,Rainfal "
    "as independent variables")
y2 = y11.describe("Labels for Crops: rice, maize, chickpea")

In [10]:
data_pointer = X11.send(duet, pointable=True)
target_pointer = y11.send(duet, pointable=True)

In [11]:
# Once uploaded, the data owner can see the object stored in the tensor
duet.store

[<syft.proxy.torch.TensorPointer object at 0x7fb069bf07d0>, <syft.proxy.torch.TensorPointer object at 0x7fb06a14ead0>]

In [12]:
# To see it in a human-readable format, data owner can also pretty-print the tensor information
duet.store.pandas

ID            Tags  \
0  <UID: 0e3419be89044758b740b812bcd507df>    [Crops-data]   
1  <UID: fed555467b904e7e85f501973e02ab65>  [Crops-target]   

                                         Description             object_type  
0  This is a dataset for Crops classification tem...  <class 'torch.Tensor'>  
1            Labels for Crops: rice, maize, chickpea  <class 'torch.Tensor'>

# Response to request coming from data scientist

In [13]:
duet.requests.add_handler(action="accept")